### PR TITLE
Implemented a component Item to use in select and radio #33

### PR DESCRIPTION
**Pull request by alexmsilva**

### CODE REVIEW

**Comment by rodrigowbazevedo** [comment]
Maybe Option is a better name...

**Comment by gabrielrcouto** [comment]
Thank you @alexmsilva, nice PR! I agree with @rodrigowbazevedo. Could you please change the class name to "Option"?

**Comment by alexmsilva** [comment]
Yes sure, I can do this. But, in the Radio class and Select class there's a method called setItems, shouldn't be better rename those methods?

**Comment by rodrigowbazevedo** [comment]
I agree with you @alexmsilva maybe it'll be better to rename these methods. What do you think @gabrielrcouto ?
In the class instead of property `id` what do you think to rename to `value`?

**Comment by gabrielrcouto** [comment]
Yeah, I agree with @alexmsilva

**Comment by reisraff** [comment]
I guess its done :P

**Pull request merged**
