### PR TITLE
Rebuild Windows binaries

### PR DESCRIPTION
**Pull request by Pierstoval**
I have Windows 10 so I'm not sure it's viable (maybe a binary for each Windows version should be used?).

`php-gui` was working but no interaction was possible in the app: button events didn't work, neither did animations, etc.

I decided to rebuild the windows binaries and publish them. Feel free to discard this PR if it wasn't the thing to do :)

ping @gabrielrcouto @reisraff

### CODE REVIEW

**Comment by reisraff** [comment]
Oh... we need to do this test, try to run all examples, in multiple versions of windows but with the same binary to check if we need one binary for each version.

**Comment by Pierstoval** [comment]
Is there a way to connect the project with AppVeyor and make tests there? 

Else, for binaries, maybe they could be built on AppVeyor and sent to Github via the release API so we could use multiple Windows versions on AppVeyor and deploy a binary for Windows 7 & Windows 10?

**Comment by reisraff** [comment]
Nice, I had never heared about, but yes we can.

**Comment by gabrielrcouto** [comment]
Thank you very much @Pierstoval, I'll setup AppVeyor for binaries build, it will be more secure for everyone.

**Pull request closed without merging**
