### PR TITLE
CS fixes for source code, and added some good practices

### PR DESCRIPTION
**Pull request by Pierstoval**
The source code has some issues with IDE implementation, good practices and auto-completion sometimes.

This PR fixes it.

ping @gabrielrcouto @reisraff

### CODE REVIEW

**Comment by reisraff** [comment]
I like your PR but we need all docblock for documentation

**Comment by Pierstoval** [comment]
The thing with doc blocks is that they're useless when properties are defined in the constructor. Unless you hack the class using the Reflection API, these properties should not change their type from the moment the object is instantiated until the property is used. So the documentation is already in the constructor. It's similar for PHP7+ projects: type hint & return type make the documentation. If it's not enough, phpdoc can be added (like for arrays of objects, for example).

But I can bring the properties phpdoc if you think this is _really_ important.

**Comment by Pierstoval** [comment]
@reisraff I decided that it would be much easier to review php-cs-fixer config instead of reviewing **all** files, so I added a php-cs-fixer config and executed it, hope you like it 👍

**Comment by Pierstoval** [comment]
Wow, seems like the force-push closed the PR, I don't know why 😕

**Pull request closed without merging**
