### PR TITLE
Create InputSpin.php

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by reisraff** [comment]
please fix those issues

**Comment by WinterSilence** [comment]
@reisraff fix if u want, i use other code style

**Comment by Luxian** [comment]
> @reisraff fix if u want, i use other code style

[sarcasm]
wow! how respectful!
[/sarcasm]

**Comment by WinterSilence** [comment]
@Luxian it's open source: code without errors, if u want format in other style, then do it self, it's no need for me

**Comment by kingga** [comment]
I have fixed up these issues in my own fork if he doesn't fix it in his in a few days I make a PR for mine.

**Pull request closed without merging**
