### PR TITLE
Implemented ProgressBar component

### PR DESCRIPTION
**Pull request by PeratX**
#82

### CODE REVIEW

**Comment by PeratX** [comment]
There is also Max and Min properties can be set. If you want to add them, pin me. xD

**Comment by gabrielrcouto** [comment]
@PeratX Really nice, thank you!

Could you please implement the max and min? With these properties, the component will be simple to use.

**Comment by PeratX** [comment]
BTW, binaries should be re-compiled after merging this PR.

**Comment by PeratX** [comment]
@gabrielrcouto friendly pin xD

**Comment by gabrielrcouto** [comment]
@PeratX really thank you! 

About BorderIcons and BorderStyle: Totally agree.

**Pull request merged**
