### PR TITLE
TDirectoryEdit implemented as DirectoryField.

### PR DESCRIPTION
**Pull request by everton3x**
DirectoryField provides a one-button text field for directory selection.

### CODE REVIEW

**Comment by everton3x** [comment]
The _getValue()_ method throws an exception in Windows because Windows uses "\" in directory paths and causes _json_decode_ to return a syntax error.

I have not yet identified a form of correction. Help is welcome.

**Comment by reisraff** [comment]
Hello @everton3x you can add a patch in unitipcthread.pas:539 where we are returning the object's property value, so there you can implement the replace, in this case replacing " to \"

**Comment by everton3x** [comment]
Thank you reisraff. Bug(?!) fixed.

I'm not very good at Pascal. Actually, I've never worked with it. I was looking for a solution in PHP code.

**Comment by reisraff** [comment]
Thank you too for your contribution, so now take a look in these build errors https://travis-ci.org/gabrielrcouto/php-gui/jobs/201973404, please fix them and update this PR.

**Comment by reisraff** [comment]
Thanks... now is just wait for it be merged.

**Comment by gabrielrcouto** [comment]
Thank you @everton3x and @reisraff for the nice work on this PR :-)

**Pull request merged**
