### PR TITLE
Make the loop property protected

### PR DESCRIPTION
**Pull request by davidwdan**
Also, added `getLoop` method to `Application` and updated the examples

see https://github.com/gabrielrcouto/php-gui/pull/49#issuecomment-208435396

### CODE REVIEW

**Comment by renatomefidf** [comment]
The code seems good and compliant with the comment mentioned.
I think that might be interesting to provide tests for that, mainly the usage of providing an already initialized loop. But its up to the maintainer of course.

**Comment by reisraff** [comment]
I agree with @renatomefidf and should be amazing we start to create tests since now.

**Comment by gabrielrcouto** [comment]
Thank you @davidwdan for this PR.

I think we can start implementing the tests too, but not touching the IPC protocol (which will be refactored).

@reisraff: Could you, please, open an issue listing all the tests we need?

**Comment by reisraff** [comment]
@gabrielrcouto sure.

**Pull request merged**
